timetables-backend/WebApp/Controllers/GamesController.cs
 using App.Contracts.BLL;
using App.Domain.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApp.Areas.ContestAdmin.ViewModels;

namespace WebApp.Controllers
{
    [Authorize]
    public class GamesController : Controller
    {
        private readonly IAppBLL _bll;
        private readonly UserManager<AppUser> _userManager;
        private Guid UserId => Guid.Parse(_userManager.GetUserId(User)!);

        public GamesController(UserManager<AppUser> userManager, IAppBLL bll)
        {
            _userManager = userManager;
            _bll = bll;
        }

        // GET: Games
        public async Task<IActionResult> Index(Guid contestId)
        {
            var contest = _bll.Contests.FirstOrDefaultAsync(contestId).Result!;
            var teachers = (await _bll.UserContestPackages.GetContestTeachers(contestId)).ToList();
            var allDays = new List<DateTime>();
            for (var date = contest.From.Date; date <= contest.Until.Date; date = date.AddDays(1))
            {
                allDays.Add(date);
            }
            var vm = new GameIndexViewModel()
            {
                Games = (await _bll.Games.GetUserContestGames(contestId, UserId)).ToList(),
                Contest = contest,
                GameTypes = (await _bll.GameTypes.GetAllCurrentContestAsync(contestId)).ToList(),
                Days = allDays,
                Times = (await _bll.Times.GetAllCurrentContestAsync(contestId)).ToList(),
                Teachers = teachers,
                TeacherIds = teachers.Select(e => e.AppUserId).ToList()
            };
            return View(vm);
        }
    }
}

timetables-backend/WebApp/Controllers/RolePreferencesController.cs
using App.BLL.DTO;
using App.Contracts.BLL;
using App.Domain.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Areas.ContestAdmin.ViewModels;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize]
    public class RolePreferencesController : Controller
    {
        private readonly IAppBLL _bll;
        private readonly UserManager<AppUser> _userManager;
        
        private Guid UserId => Guid.Parse(_userManager.GetUserId(User)!);

        public RolePreferencesController(UserManager<AppUser> userManager, IAppBLL bll)
        {
            _userManager = userManager;
            _bll = bll;
        }

        // GET: RolePreferences/Create
        public async Task<IActionResult> Create(Guid contestId)
        {
            var gameTypes = (await _bll.GameTypes.GetAllCurrentContestAsync(contestId)).ToList();
            var levelSelectList = new SelectList(await _bll.Levels.GetAllCurrentContestAsync(contestId), nameof(Level.Id), nameof(Level.Title));
            var selectedLevelsList = new List<List<Guid>>(gameTypes.Count);
            var previousRolePreferences = (await _bll.RolePreferences.GetAllAsync(UserId)).ToList();
    
            for (int i = 0; i < gameTypes.Count; i++)
            {
                selectedLevelsList.Add(new List<Guid>());
            }

            var vm = new RolePreferenceCreateEditViewModel()
            {
                ContestId = contestId.ToString(),
                GameTypes = gameTypes,
                LevelSelectList = levelSelectList,
                SelectedLevelsList = selectedLevelsList, 
                PreviousRolePreferences = previousRolePreferences
            };
            return View(vm);
        }

        // POST: RolePreferences/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RolePreferenceCreateEditViewModel vm)
        {
            //Remove previous rolepreferences
            var rolePreferences = (await _bll.RolePreferences.GetAllAsync(UserId)).ToList();
            foreach (var role in rolePreferences)
            {
                await _bll.RolePreferences.RemoveAsync(role);
            }
            
            var gameTypes = (await _bll.GameTypes.GetAllCurrentContestAsync(Guid.Parse(vm.ContestId))).ToList();
            
            for(var i = 0; i < gameTypes.Count; i++)
            {
                foreach (var levelId in vm.SelectedLevelsList[i])
                {
                    if (levelId.ToString() == "-1")
                    {
                        break;
                    }
                    var rolePreference = new RolePreference
                    {
                        LevelId = levelId,
                        GameTypeId = gameTypes[i].Id,
                        ContestId = Guid.Parse(vm.ContestId)
                    };
                    _bll.RolePreferences.AddRolePreferenceWithUser(Guid.Parse(_userManager.GetUserId(User)!), rolePreference);
                }
            }
            await _bll.SaveChangesAsync(); 
            return RedirectToAction("MyContests", "Contests");
        }
    }
}

timetables-backend/WebApp/Controllers/UserContestPackagesController.cs
using App.Contracts.BLL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using App.BLL.DTO;
using App.Domain.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using WebApp.ViewModels;
using Contest = App.Domain.Contest;

namespace WebApp.Controllers
{
    [Authorize]
    public class UserContestPackagesController : Controller
    {
        private readonly IAppBLL _bll;
        private readonly UserManager<AppUser> _userManager;

        public UserContestPackagesController(IAppBLL bll, UserManager<AppUser> userManager)
        {
            _bll = bll;
            _userManager = userManager;
        }
        
        // GET: UserContestPackages/Create
        public async Task<IActionResult> Create(Guid contestId)
        {
            var vm = new UserContestPackageCreateViewModel()
            { 
                LevelSelectList = new SelectList(await _bll.Levels.GetAllCurrentContestAsync(contestId),nameof(Level.Id),
                    nameof(Level.Title)),
                PackageGameTypeTimeSelectList = new SelectList(await _bll.PackageGameTypeTimes.GetAllCurrentContestAsync(contestId), nameof(PackageGameTypeTime.Id),
                    nameof(PackageGameTypeTime.PackageGtName)),
                Contest = await _bll.Contests.FirstOrDefaultAsync(contestId),
            };
            return View(vm);
        }

        // POST: UserContestPackages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserContestPackageCreateViewModel vm)
        {
            var userId = Guid.Parse(_userManager.GetUserId(User)!);
            if (ModelState.IsValid)
            {
                //Osavõtja roll
                var participantRoleId = await _bll.ContestRoles.ContestRoleId("Participant");
                var participantUserRole = new ContestUserRole
                {
                    ContestRoleId = participantRoleId,
                    AppUserId = userId
                };
                _bll.ContestUserRoles.Add(participantUserRole);


                var packageGameType = await _bll.PackageGameTypeTimes.FirstOrDefaultAsync(vm.UserContestPackage.PackageGameTypeTimeId);
                var contest = await _bll.Contests.FirstOrDefaultAsync(vm.UserContestPackage.ContestId);
                var level = await _bll.Levels.FirstOrDefaultAsync(vm.UserContestPackage.LevelId);
                
                var team = new Team()  // Create team
                {
                    Id = Guid.NewGuid(),
                    TeamName = _userManager.GetUserName(User) + " team",
                    LevelId = level!.Id,
                    GameTypeId = packageGameType!.GameTypeId,
                };
                _bll.Teams.Add(team);
                
                vm.UserContestPackage.Id = Guid.NewGuid();
                vm.UserContestPackage.HoursAvailable = contest!.TotalHours * packageGameType.Times;
                vm.UserContestPackage.AppUserId = userId;
                vm.UserContestPackage.TeamId = team.Id;
                _bll.UserContestPackages.Add(vm.UserContestPackage);
                await _bll.SaveChangesAsync();
                
                /*
                //Create all times for team
                var timeOfDays = _bll.TimeOfDays.GetAllAsync().Result.ToList();
                var contestStartDate = contest.From.Date;
                var contestEndDate = contest.Until.Date;
                var contestLength = (contestEndDate - contestStartDate).TotalDays;

                for (int i = 0; i <= contestLength; i++)
                {
                    foreach (var timeOfDay in timeOfDays)
                    {
                        _bll.TimeTeams.Add(new TimeTeam
                        {
                            TimeOfDayId = timeOfDay.Id,
                            Day = DateOnly.FromDateTime (contestStartDate.AddDays(i)),
                            TeamId = team.Id,
                        });
                    }
                }
                */
                
                await _bll.SaveChangesAsync();
                return RedirectToAction("MyContests", "Contests");
            }
            vm.PackageGameTypeTimeSelectList = new SelectList(await _bll.PackageGameTypeTimes.GetAllAsync(userId), nameof(PackageGameTypeTime.Id),
                nameof(PackageGameTypeTime.PackageGtName));
            vm.Contest = await _bll.Contests.FirstOrDefaultAsync(vm.UserContestPackage.ContestId);
            vm.LevelSelectList = new SelectList(await _bll.Levels.GetAllCurrentContestAsync(vm.UserContestPackage.ContestId), nameof(Level.Id),
                nameof(Level.Title));
            return View(vm);
        }
        
        // GET: UserContestPackages/Invite
        public async Task<IActionResult> Invite(Guid contestId, Guid teamId)
        {
            var users = _bll.UserContestPackages.GetContestTeammates(contestId, teamId).Result
                .Select(e => e.AppUserId).ToList();
            
            var vm = new UserTeamCreateViewModel()
            {
                ContestId = contestId,
                TeamId = teamId,
                UserContestPackageSelectList = (await _bll.UserContestPackages.GetContestParticipants(contestId))
                    .Where(e => !users.Contains(e.AppUserId))
                    .Select(e => new SelectListItem() {Text = e.AppUser!.FirstName + ' ' + e.AppUser!.LastName , Value = e.Id.ToString()}).ToList()
            };
            return View(vm);
        }

        // POST: UserContestPackages/Invite
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Invite(UserTeamCreateViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var package = await _bll.UserContestPackages.FirstOrDefaultAsync(vm.UserContestPackageId);
                var appUserId = package!.AppUserId;

                var newPackage = new UserContestPackage
                {
                    PackageGameTypeTimeId = package.PackageGameTypeTimeId,
                    HoursAvailable = 0,
                    ContestId = package.ContestId,
                    TeamId = vm.TeamId,
                    LevelId = package.LevelId,
                };

                _bll.UserContestPackages.AddPackageWithUser(appUserId, newPackage);

                //Get Previous Team
                var previousTeamId =
                    _bll.UserContestPackages.GetUserContestPackage(vm.ContestId, appUserId).Result!.TeamId;
                
                //Delete previous TimeTeams
                await _bll.TimeTeams.RemoveTeamTimeTeamsAsync(previousTeamId);
                
                //Delete previous package
                await _bll.UserContestPackages.RemoveAsync(package);
                
                //Delete previous Team
                await _bll.Teams.RemoveAsync(previousTeamId);
                
                await _bll.SaveChangesAsync();
                return RedirectToAction("MyContests", "Contests");
            }

            var userId = _bll.UserContestPackages.FirstOrDefaultAsync(vm.UserContestPackageId).Result!.AppUserId;
            vm.UserContestPackageSelectList = new SelectList(await _bll.UserContestPackages.GetAllAsync(userId),
                nameof(UserContestPackage.Id),
                nameof(UserContestPackage.AppUser));
            vm.ContestId = vm.ContestId;
            vm.TeamId = vm.TeamId;
            return RedirectToAction("MyContests", "Contests");
        }
/*
        // GET: UserContestPackages/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userContestPackage = await _context.UserContestPackages.FindAsync(id);
            if (userContestPackage == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = new SelectList(_context.AppUsers, "Id", "FirstName", userContestPackage.AppUserId);
            ViewData["ContestId"] = new SelectList(_context.Contests, "Id", "Description", userContestPackage.ContestId);
            ViewData["LevelId"] = new SelectList(_context.Levels, "Id", "Description", userContestPackage.LevelId);
            ViewData["PackageGameTypeTimeId"] = new SelectList(_context.PackageGameTypeTimes, "Id", "PackageGtName", userContestPackage.PackageGameTypeTimeId);
            return View(userContestPackage);
        }

        // POST: UserContestPackages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("PackageGameTypeTimeId,HoursAvailable,AppUserId,ContestId,LevelId,Id")] UserContestPackage userContestPackage)
        {
            if (id != userContestPackage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userContestPackage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserContestPackageExists(userContestPackage.Id))
                    {
                        return NotFound();
                    }
                    else

timetables-backend/WebApp/Views/Contests/MyContests.cshtml
@model WebApp.ViewModels.ContestMyContestsViewModel

@{
    ViewData["Title"] = App.Resources.Views.Shared._Layout.Contests;
}

<h1 class="middle">@App.Resources.Views.Shared._Layout.My @App.Resources.Views.Shared._Layout.Contests</h1>

<br/>
<br/>


@if (Model.CurrentContests.Count > 0)
{
    <div class="ended-contests">
        <h2 class="section-title">@App.Resources.Views.Shared._Layout.CurrentContests</h2>

        <div class="row">
            @foreach (var contest in Model.CurrentContests)
            {
                <div class="col-md-6 mb-4">
                    <div class="card ended-contest-card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">

                                    @if (contest.IfTrainer)
                                    {
                                        <h2 class="contest-name">@contest.Contest.ContestName - @App.Resources.Views.Shared._Layout.Trainer</h2>
                                    }
                                    else
                                    {
                                        <h2 class="contest-name">@contest.Contest.ContestName</h2>
                                    }
                                    
                                    <p class="contest-duration">@contest.Contest.From - @contest.Contest.Until</p>

                                    @if (contest.IfTrainer)
                                    {
                                        <div>

                                            @foreach (var gameType in contest.GameTypes)
                                            {
                                                var selectedTitles = Model.RolePreferences!
                                                    .Where(e => e.ContestId.Equals(contest.Contest.Id) 
                                                                && e.GameTypeId.Equals(gameType.Id))
                                                    .OrderBy(e => e.Level!.Title.ToString())
                                                    .Select(e => e.Level!.Title)
                                                    .ToList();
                                                <p class="contest-detail">
                                                    <strong>@gameType.GameTypeName:</strong>
                                                    <p>
                                                        @(selectedTitles.Any() ? string.Join(", ", selectedTitles) : "None")
                                                    </p>
                                                </p>
                                            }
                                        </div>
                                    }
                                    else
                                    {
                                        <p class="contest-detail">
                                            <strong>@App.Resources.Views.Shared._Layout.Level:</strong> @contest.Level.Title
                                        </p>
                                        <p class="contest-detail">
                                            <strong>@App.Resources.Views.Shared._Layout.GameType:</strong> @contest.GameType.GameTypeName
                                        </p>
                                        <p class="contest-detail">
                                            <strong>@App.Resources.Views.Shared._Layout.Package:</strong> @contest.PackageGameTypeTime.PackageGtName
                                        </p>
                                    }
                                    @if (contest.AnyGames)
                                    {
                                        <div class="contest-actions">
                                            <a class="btn btn-primary" asp-controller="Games" asp-action="Index" asp-route-contestId="@contest.Contest.Id">@App.Resources.Views.Shared._Layout.Games</a>
                                        </div>
                                    }
                                    
                                </div>

                                @if (!contest.IfTrainer)
                                {
                                    <div class="col-md-6">

                                        <h4>@App.Resources.Views.Shared._Layout.Teammates</h4>
                                        <ul class="team-members">
                                            @foreach (var userPackage in contest.UserContestPackages)
                                            {
                                                <li>@userPackage.AppUser!.FirstName @userPackage.AppUser!.LastName</li>
                                            }
                                        </ul>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}


@if (Model.ComingContests.Count > 0)
{
    <div class="ended-contests">
        <h2 class="section-title">@App.Resources.Views.Shared._Layout.UpcomingContests</h2>

        <div class="row">
            @foreach (var contest in Model.ComingContests)
            {
                <div class="col-md-7 mb-4">
                    <div class="card ended-contest-card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    @if (contest.IfTrainer)
                                    {
                                        <h2 class="contest-name">@contest.Contest.ContestName - @App.Resources.Views.Shared._Layout.Trainer</h2>
                                    }
                                    else
                                    {
                                        <h2 class="contest-name">@contest.Contest.ContestName</h2>
                                    }
                                    <p class="contest-duration">@contest.Contest.From - @contest.Contest.Until</p>
                                    @if (contest.IfTrainer)
                                    {
                                        <div>
                                            @foreach (var gameType in contest.GameTypes)
                                            {
                                                var selectedTitles = Model.RolePreferences!
                                                    .Where(e => e.ContestId.Equals(contest.Contest.Id) && 
                                                                e.GameTypeId.Equals(gameType.Id))
                                                    .OrderBy(e => e.Level!.Title.ToString())
                                                    .Select(e => e.Level!.Title)
                                                    .ToList();
                                                <p class="contest-detail">
                                                    <strong>@gameType.GameTypeName:</strong>
                                                    <p>@(selectedTitles.Any() ? string.Join(", ", selectedTitles) : "None")</p>
                                                </p>
                                            }
                                        </div>
                                        <div class="contest-actions">
                                            @if (contest.AnyGames)
                                            {
                                                <a class="btn btn-primary" asp-controller="Games" asp-action="Index" asp-route-contestId="@contest.Contest.Id">@App.Resources.Views.Shared._Layout.Games</a>
                                            }
                                            <a class="btn btn-primary" asp-controller="RolePreferences" asp-action="Create" asp-route-contestId="@contest.Contest.Id">@App.Resources.Views.Shared._Layout.Trainer_Preferences</a>
                                        </div>
                                    }
                                    else
                                    {
                                        <p class="contest-detail">
                                            <strong>@App.Resources.Views.Shared._Layout.Level:</strong> @contest.Level.Title
                                        </p>
                                        <p class="contest-detail">
                                            <strong>@App.Resources.Views.Shared._Layout.GameType:</strong> @contest.GameType.GameTypeName
                                        </p>
                                        <p class="contest-detail">
                                            <strong>@App.Resources.Views.Shared._Layout.Package:</strong> @contest.PackageGameTypeTime.PackageGtName
                                        </p>
                                        <div class="contest-actions">

                                            @if (contest.AnyGames)
                                            {
                                                <a class="btn btn-primary" asp-controller="Games" asp-action="Index" asp-route-contestId="@contest.Contest.Id">@App.Resources.Views.Shared._Layout.Games</a>
                                            }
                                            <a id="addTeammates" class="btn btn-success" asp-controller="UserContestPackages" asp-action="Invite" asp-route-contestId="@contest.Contest.Id" asp-route-teamId="@contest.UserContestPackage.TeamId">@App.Resources.Views.Shared._Layout.AddTeamMates</a>
                                        </div>
                                    }
                                </div>
                                @if (!contest.IfTrainer)
                                {
                                    <div class="col-md-6">

                                        <h4>@App.Resources.Views.Shared._Layout.Teammates</h4>
                                        <ul class="team-members">
                                            @foreach (var userPackage in contest.UserContestPackages)
                                            {
                                                <li>@userPackage.AppUser!.FirstName @userPackage.AppUser!.LastName</li>
                                            }
                                        </ul>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}


@if (Model.EndedContests.Count > 0)
{
    <div class="ended-contests">
        <h2 class="section-title">@App.Resources.Views.Shared._Layout.Finished_contests</h2>

        <div class="row">
            @foreach (var contest in Model.EndedContests)
            {
                <div class="col-md-6 mb-4">
                    <div class="card ended-contest-card">
                        <div class="card-body">
                            <h2 class="contest-name">@contest.ContestName</h2>
                            <p class="contest-duration">@contest.From - @contest.Until</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}