timetables-backend/WebApp/Areas/ContestAdmin/Controllers/ContestsController.cs
using App.BLL.DTO;
using App.Contracts.BLL;

using App.Domain.Identity;
using Base.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Areas.ContestAdmin.ViewModels;

namespace WebApp.Areas.ContestAdmin.Controllers
{
    [Authorize(Roles = "Contest Admin")]
    [Area("ContestAdmin")]
    public class ContestsController : Controller
    {
        private readonly IAppBLL _bll;
        private readonly UserManager<AppUser> _userManager;

        private Guid UserId => Guid.Parse(_userManager.GetUserId(User)!);

        public ContestsController(UserManager<AppUser> userManager, IAppBLL bll)
        {
            _userManager = userManager;
            _bll = bll;
        }


        // GET: Contests
        public async Task<IActionResult> Index()
        {
            var contest = await _bll.Contests.GetAllAsync(UserId);

            foreach (var contestInfo in contest)
            {
                contestInfo.From = contestInfo.From.ToUniversalTime();
                contestInfo.Until = contestInfo.Until.ToUniversalTime();
            }

            return View(contest);
        }
        // GET: Contests/Overview
        public async Task<IActionResult> OverView(Guid contestId)
        {
            var contest = await _bll.Contests.FirstOrDefaultAsync(contestId);
            contest!.From = contest.From.ToUniversalTime();
            contest.Until = contest.Until.ToUniversalTime();

            var vm = new ContestOverviewViewModel
            {
                Contest = contest,
                Teams = _bll.Teams.GetAllCurrentContestAsync(contest.Id).Result.ToList(),
                UserContestPackages =
                    _bll.UserContestPackages.GetContestParticipants(contest.Id).Result.ToList(),
                GameTypes = _bll.GameTypes.GetAllCurrentContestAsync(contest.Id).Result.ToList(),
                Teachers = _bll.UserContestPackages.GetContestTeachers(contest.Id).Result.ToList(),
                Levels = _bll.Levels.GetAllCurrentContestAsync(contest.Id).Result.ToList(),
            };
            
            return View(vm);
        }

        // GET: Contests/Create
        public async Task<IActionResult> Create()
        {
            var times = await _bll.Times.GetAllAsync(UserId);
            var vm = new ContestCreateEditViewModel()
            {
                ContestTypeSelectList = new SelectList(
                    await _bll.ContestTypes.GetAllAsync(UserId),
                    nameof(ContestType.Id),
                    nameof(ContestType.ContestTypeName)),
                LocationSelectList = new SelectList(
                    await _bll.Locations.GetAllAsync(UserId), nameof(Location.Id),
                    nameof(Location.LocationName)),
                LevelSelectList = new SelectList(
                    await _bll.Levels.GetAllAsync(UserId), nameof(Level.Id),
                    nameof(Level.Title)),
                TimesSelectList = new SelectList(times.Select(t => new {t.Id, DisplayText = $"{t.From} - {t.Until}" }), "Id", "DisplayText"),
                PackagesSelectList =
                    new SelectList(
                        await _bll.PackageGameTypeTimes.GetAllAsync(UserId),
                        nameof(PackageGameTypeTime.Id), nameof(PackageGameTypeTime.PackageGtName))
            };
            return View(vm);
        }

        // POST: Contests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ContestCreateEditViewModel vm)
        {
            if (ModelState.IsValid)
            {
                if (vm.SelectedLevelIds!.Count < 1 || vm.SelectedTimesIds!.Count < 1 ||
                    vm.SelectedPackagesIds!.Count < 1)
                {
                    return View(vm);
                }

                vm.Contest.Id = Guid.NewGuid();
                vm.Contest.From = vm.Contest.From.ToUniversalTime();
                vm.Contest.Until = vm.Contest.Until.ToUniversalTime();

                foreach (var levelId in vm.SelectedLevelIds!)
                {
                    var contestLevel = new ContestLevel
                    {
                        ContestId = vm.Contest.Id,
                        LevelId = levelId
                    };
                    _bll.ContestLevels.Add(contestLevel);
                }

                var gameTypes = new HashSet<Guid>();
                var allPackages = (await _bll.PackageGameTypeTimes.GetAllAsync(default)).ToList();

                foreach (var id in vm.SelectedPackagesIds)
                {
                    var gameTypeId = allPackages.FirstOrDefault(e => e.Id.Equals(id) && !gameTypes.Contains(e.GameTypeId))?.GameTypeId;
    
                    if (gameTypeId != null)
                    {
                        gameTypes.Add(gameTypeId.Value);
                    }
                }
                
                foreach (var gameTypeId in gameTypes)
                {
                    var contestGameType = new ContestGameType()
                    {
                        ContestId = vm.Contest.Id,
                        GameTypeId = gameTypeId
                    };
                    _bll.ContestGameTypes.Add(contestGameType);
                }

                foreach (var timeId in vm.SelectedTimesIds!)
                {
                    var times = new ContestTime()
                    {
                        ContestId = vm.Contest.Id,
                        TimeId = timeId
                    };
                    _bll.ContestTimes.Add(times);
                }

                foreach (var packageId in vm.SelectedPackagesIds!)
                {
                    var package = new ContestPackage()
                    {
                        ContestId = vm.Contest.Id,
                        PackageGameTypeTimeId = packageId
                    };
                    _bll.ContestPackages.Add(package);
                }
                 
                //Contest Roles by default
                var trainerRole = new ContestRole
                {
                    ContestRoleName = "Trainer",
                    ContestId = vm.Contest.Id
                };

                var participantRole = new ContestRole()
                {
                    ContestRoleName = "Participant",
                    ContestId = vm.Contest.Id
                };
                _bll.ContestRoles.Add(participantRole);
                _bll.ContestRoles.Add(trainerRole);
                
                
                _bll.Contests.AddContestWithUser(UserId, vm.Contest);
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            vm.ContestTypeSelectList = new SelectList(
                await _bll.ContestTypes.GetAllAsync(UserId), nameof(ContestType.Id),
                nameof(ContestType.ContestTypeName));
            vm.LocationSelectList = new SelectList(
                await _bll.Locations.GetAllAsync(UserId), nameof(Location.Id),
                nameof(Location.LocationName));
            vm.LevelSelectList = new SelectList(await _bll.Levels.GetAllAsync(UserId),
                nameof(Level.Id),
                nameof(Level.Title));
            vm.TimesSelectList =
                new SelectList(await _bll.Times.GetAllAsync(UserId),
                    nameof(TimeOfDay.Id), nameof(TimeOfDay.TimeOfDayName));
            vm.PackagesSelectList =
                new SelectList(await _bll.PackageGameTypeTimes.GetAllAsync(UserId),
                    nameof(PackageGameTypeTime.Id), nameof(PackageGameTypeTime.PackageGtName));
            return View(vm);
        }

        // GET: Contests/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == null || !_bll.Contests.IsContestOwnedByUser(UserId, id))
            {
                return NotFound();
            }
            var contest = await _bll.Contests.FirstOrDefaultAsync(id, UserId);
            if (contest == null)
            {
                return NotFound();
            }
            
            var previousLevels = (await _bll.Contests.FirstOrDefaultAsync(id, UserId))!.ContestLevels.Select(e => e.Level).ToList();
            var previousPackages = (await _bll.Contests.FirstOrDefaultAsync(id, UserId))!.ContestPackages.Select(e => e.PackageGameTypeTime).ToList();
            var previousTimes = (await _bll.Contests.FirstOrDefaultAsync(id, UserId))!.ContestTimes.Select(e => e.Time).ToList();

            var vm = new ContestCreateEditViewModel()
            {
                Contest = contest,
                ContestTypeSelectList = new SelectList(
                    await _bll.ContestTypes.GetAllAsync(UserId),
                    nameof(ContestType.Id),
                    nameof(ContestType.ContestTypeName)),
                LocationSelectList = new SelectList(
                    await _bll.Locations.GetAllAsync(UserId), nameof(Location.Id),
                    nameof(Location.LocationName)),
                LevelSelectList = new SelectList(
                    await _bll.Levels.GetAllAsync(UserId),
                    nameof(Level.Id),
                    nameof(Level.Title)),
                TimesSelectList = 
                    new SelectList(await _bll.Times.GetAllAsync(UserId),
                        nameof(Time.Id), nameof(Time.From)),
                PackagesSelectList =
                    new SelectList(
                        await _bll.PackageGameTypeTimes.GetAllAsync(UserId),
                        nameof(PackageGameTypeTime.Id), nameof(PackageGameTypeTime.PackageGtName)),

timetables-backend/WebApp/Controllers/GamesController.cs
 using App.Contracts.BLL;
using App.Domain.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApp.Areas.ContestAdmin.ViewModels;

namespace WebApp.Controllers
{
    [Authorize]
    public class GamesController : Controller
    {
        private readonly IAppBLL _bll;
        private readonly UserManager<AppUser> _userManager;
        private Guid UserId => Guid.Parse(_userManager.GetUserId(User)!);

        public GamesController(UserManager<AppUser> userManager, IAppBLL bll)
        {
            _userManager = userManager;
            _bll = bll;
        }

        // GET: Games
        public async Task<IActionResult> Index(Guid contestId)
        {
            var contest = _bll.Contests.FirstOrDefaultAsync(contestId).Result!;
            var teachers = (await _bll.UserContestPackages.GetContestTeachers(contestId)).ToList();
            var allDays = new List<DateTime>();
            for (var date = contest.From.Date; date <= contest.Until.Date; date = date.AddDays(1))
            {
                allDays.Add(date);
            }
            var vm = new GameIndexViewModel()
            {
                Games = (await _bll.Games.GetUserContestGames(contestId, UserId)).ToList(),
                Contest = contest,
                GameTypes = (await _bll.GameTypes.GetAllCurrentContestAsync(contestId)).ToList(),
                Days = allDays,
                Times = (await _bll.Times.GetAllCurrentContestAsync(contestId)).ToList(),
                Teachers = teachers,
                TeacherIds = teachers.Select(e => e.AppUserId).ToList()
            };
            return View(vm);
        }
    }
}

timetables-backend/WebApp/Areas/ContestAdmin/Views/Contests/Create.cshtml
@model WebApp.Areas.ContestAdmin.ViewModels.ContestCreateEditViewModel

@{
    ViewData["Title"] = @App.Resources.Views.Shared._Layout.Contest;
}

<h1 class="middle">@App.Resources.Views.Shared._Layout.Create @App.Resources.Views.Shared._Layout.New @App.Resources.Views.Shared._Layout.Contest</h1>

<hr/>
<form asp-action="Create">
    <partial name="_CreateEdit" model="Model"/>

    <div class="form-group middle">
        <input type="submit" value="Create" class="btn btn-primary"/>
    </div>
</form>

<div asp-validation-summary="All" class="text-danger"></div>

<div>
    <a class="middle" asp-action="Index">@App.Resources.Views.Shared._Layout.Back_To_List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

timetables-backend/WebApp/Areas/ContestAdmin/Views/Contests/Delete.cshtml
@model App.BLL.DTO.Contest

@{
    ViewData["Title"] = @App.Resources.Views.Shared._Layout.Contest;
}

<h1 class="middle">@App.Resources.Views.Shared._Layout.Delete @App.Resources.Views.Shared._Layout.Contest</h1>

<div>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <dl class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <dt class="col-sm-4">
                            @App.Resources.Domain.Contest.ContestName
                        </dt>
                        <dd class="col-sm-8">
                            @Model.ContestName
                        </dd>
                        <dt class="col-sm-4">
                            @App.Resources.Domain.Contest.Description
                        </dt>
                        <dd class="col-sm-8">
                            @Model.Description
                        </dd>
                        <dt class="col-sm-4">
                            @App.Resources.Domain.Contest.From
                        </dt>
                        <dd class="col-sm-8">
                            @Model.From)
                        </dd>
                        <dt class="col-sm-4">
                            @App.Resources.Domain.Contest.Until
                        </dt>
                        <dd class="col-sm-8">
                            @Model.Until)
                        </dd>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.TotalHours)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.TotalHours)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.ContestType)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.ContestType!.ContestTypeName)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Location)
                        </dt>
                        <dd class="col-sm-8">
                            @Model.Location!.LocationName)
                        </dd>
                    </div>
                </div>
            </div>
        </dl>
        <div class="middle">

            <input type="submit" value="Delete" class="btn btn-danger middle" /> <a asp-action="Index">@App.Resources.Views.Shared._Layout.Back_To_List</a>
        </div>
    </form>
</div>

timetables-backend/WebApp/Areas/ContestAdmin/Views/Contests/Edit.cshtml
@model WebApp.Areas.ContestAdmin.ViewModels.ContestCreateEditViewModel

@{
    ViewData["Title"] = @App.Resources.Views.Shared._Layout.Contest;
}

<h1 class="middle">@App.Resources.Views.Shared._Layout.Edit</h1>

<hr />
<form asp-action="Edit">
    <input type="hidden" asp-for="Contest.Id" />
    <partial name="_CreateEdit" model="Model"/>
    <div class="form-group middle">
        <input type="submit" value="@App.Resources.Views.Shared._Layout.Save" class="btn btn-primary"/>
    </div>
</form>

<div>
    <a class="middle" asp-action="Index">@App.Resources.Views.Shared._Layout.Back_To_List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

timetables-backend/WebApp/Areas/ContestAdmin/Views/Contests/Index.cshtml
@using App.Contracts.BLL
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<App.BLL.DTO.Contest>
@inject IAppBLL _bll;

@{
    ViewData["Title"] = App.Resources.Views.Shared._Layout.Contests;
    
}

<h1 class="middle">@App.Resources.Views.Shared._Layout.My @App.Resources.Views.Shared._Layout.Contests</h1>

<p>
    <a class="display-6 text-dark" asp-action="Create">@App.Resources.Views.Shared._Layout.Create @App.Resources.Views.Shared._Layout.New</a>
</p>
<br/>
<div class="container">
    <table class="table table-hover">
        <thead class="thead-dark">
        <tr>
            <th scope="col">@App.Resources.Domain.Contest.ContestName</th>
            <th scope="col">@App.Resources.Domain.Contest.From</th>
            <th scope="col">@App.Resources.Domain.Contest.Until</th>
            <th scope="col">@App.Resources.Domain.Contest.TotalHours</th>
            <th scope="col">@App.Resources.Domain.Contest.ContestTypeId</th>
            <th scope="col">@App.Resources.Domain.Contest.Location</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            var anyTeams =  _bll.UserContestPackages.AnyTeams(item.Id);
            var anyGames = _bll.Games.AnyContestGames(item.Id);
            <tr>
                <td>@item.ContestName</td>
                <td>@item.From.ToShortDateString()</td>
                <td>@item.Until.ToShortDateString()</td>
                <td>@item.TotalHours</td>
                <td>@item.ContestType!.ContestTypeName</td>
                <td>@item.Location!.LocationName</td>
                <td>
                    <a id="OverView" class="btn btn-success" asp-controller="Contests" asp-action="OverView" asp-route-contestId="@item.Id">@App.Resources.Views.Shared._Layout.Overview</a>
                    <a class="btn btn-success" asp-controller="Games" asp-action="Create" asp-route-contestId="@item.Id">@App.Resources.Views.Shared._Layout.Create_Games</a>
                        @if (anyGames)
                        {
                            <a class="btn btn-success" asp-controller="Games" asp-action="Index" asp-route-contestId="@item.Id">@App.Resources.Views.Shared._Layout.Games</a>
                        }
                    <a class="btn btn-success" asp-controller="AppUser" asp-action="Index" asp-route-contestId="@item.Id">@App.Resources.Views.Shared._Layout.Add_Trainers</a>
                    
                        @if (anyTeams)
                        {
                            <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">@App.Resources.Views.Shared._Layout.Edit</a>
                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">@App.Resources.Views.Shared._Layout.Delete</a>
                        }
                </td>
            </tr>   
        }
        </tbody >
    </table >
</div>

timetables-backend/WebApp/Areas/ContestAdmin/Views/Contests/Overview.cshtml
@model WebApp.Areas.ContestAdmin.ViewModels.ContestOverviewViewModel
@{
    ViewData["Title"] = App.Resources.Views.Shared._Layout.Contest;
}

<h1 class="middle">@App.Resources.Views.Shared._Layout.My @App.Resources.Views.Shared._Layout.Contest</h1>

<hr/>
<div class="container">
    <div class="row">
        @foreach (var gameType in Model.GameTypes)
        {
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">@gameType.GameTypeName</h5>
                        <p class="card-text">Teams Count: @Model.Teams.Count(g => g.GameTypeId == gameType.Id)</p>
                        <p class="card-text">People Count: @Model.UserContestPackages.Count(u => u.Team!.GameTypeId == gameType.Id)</p>
                        <p class="card-text">Trainers Count: @Model.Teachers.Count(e => e.AppUser!.RolePreferences.Any(e => e.GameTypeId.Equals(gameType.Id)))</p>
                        <hr>
                        <h6 class="mt-4">Tasemete järgi</h6>
                        <ul class="list-unstyled">
                            @foreach (var level in Model.Levels)
                            {
                                <li>@level.Title: @Model.UserContestPackages.Select(e => e.Team).Count(g => g!.GameTypeId == gameType.Id && g.LevelId.Equals(level.Id))</li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div>
    <a class="middle" asp-action="Index">Back to List</a>
</div>

timetables-backend/WebApp/Areas/ContestAdmin/Views/Contests/_CreateEdit.cshtml
@model WebApp.Areas.ContestAdmin.ViewModels.ContestCreateEditViewModel


<br/>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="mb-3 row">
    <div class="col-md-4">
        <div class="form-group">
            <label asp-for="Contest.ContestName" class="control-label">@App.Resources.Domain.Contest.ContestName</label>
            <input asp-for="Contest.ContestName" class="form-control" required="required"/>
            <span asp-validation-for="Contest.ContestName" class="text-danger"></span>
        </div>
        <br/>
        <div class="form-group">
            <label asp-for="Contest.From" class="control-label">@App.Resources.Domain.Contest.From</label>
            <input asp-for="Contest.From" class="form-control" required="required"/>
            <span asp-validation-for="Contest.From" class="text-danger"></span>
        </div>
        <br/>
        <div class="form-group">
            <label asp-for="Contest.LocationId" class="control-label">@App.Resources.Domain.Contest.Location</label>
            <select required="required" asp-for="Contest.LocationId" class="form-control" asp-items="Model.LocationSelectList"></select>
        </div>
        <br/>
        <div class="form-group">
            @{
                if (Model.PreviousLevels != null)
                {
                    <label class="control-label">@App.Resources.Views.Shared._Layout.Levels</label>
                    <select multiple="multiple" asp-for="SelectedLevelIds" class="form-control" required="required">
                        @foreach (var level in Model.LevelSelectList!)
                        {
                            if (Model.PreviousLevels.Any(e => e.Id.ToString().Equals(level.Value)))
                            {
                                <option selected="selected" value="@level.Value">@level.Text</option>
                            }
                            else
                            {
                                <option value="@level.Value">@level.Text</option>
                            }
                        }
                    </select>
                }
                else
                {
                    <div class="form-group">
                        <label class="control-label">@App.Resources.Views.Shared._Layout.Levels</label>
                        <select required="required" asp-for="SelectedLevelIds" class="form-control" asp-items="Model.LevelSelectList" multiple="multiple"></select>
                    </div>
                }
            }
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label asp-for="Contest.Description" class="control-label">@App.Resources.Domain.Contest.Description</label>
            <input required="required" asp-for="Contest.Description" class="form-control"/>
            <span asp-validation-for="Contest.Description" class="text-danger"></span>
        </div>
        <br/>
        <div class="form-group">
            <label asp-for="Contest.Until" class="control-label">@App.Resources.Domain.Contest.Until</label>
            <input required="required" asp-for="Contest.Until" class="form-control"/>
            <span asp-validation-for="Contest.Until" class="text-danger"></span>
        </div>
        <br/>
        <div class="form-group">
            <label asp-for="Contest.ContestTypeId" class="control-label">@App.Resources.Views.Shared._Layout.ContestTypes</label>
            <select required="required" asp-for="Contest.ContestTypeId" class="form-control" asp-items="Model.ContestTypeSelectList"></select>
        </div>
        <br/>
        <div class="form-group">
            @{
            if (Model.PreviousPackages != null)
            {
            <label class="control-label">@App.Resources.Views.Shared._Layout.Packages</label>
            <select multiple="multiple" asp-for="SelectedPackagesIds" class="form-control" required="required">
                @foreach (var package in Model.PackagesSelectList!)
                {
                if (Model.PreviousPackages.Any(e => e.Id.ToString().Equals(package.Value)))
                {
                <option selected="selected" value="@package.Value">@package.Text</option>
                }
                else
                {
                <option value="@package.Value">@package.Text</option>
                }
                }
            </select>
            }
            else
            {
            <div class="form-group">
                <label class="control-label">@App.Resources.Views.Shared._Layout.Packages</label>
                <select required="required" asp-for="SelectedPackagesIds" class="form-control" asp-items="Model.PackagesSelectList" multiple="multiple"></select>
            </div>
            }
            }
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label asp-for="Contest.TotalHours" class="control-label">@App.Resources.Domain.Contest.TotalHours</label>
            <input required="required" asp-for="Contest.TotalHours" class="form-control"/>
            <span asp-validation-for="Contest.TotalHours" class="text-danger"></span>
        </div>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <div class="form-group">
            @{
            if (Model.PreviousTimes != null)
            {
            <label class="control-label">@App.Resources.Views.Shared._Layout.Times</label>
            <select multiple="multiple" asp-for="SelectedTimesIds" class="form-control" required="required">
                @foreach (var time in Model.TimesSelectList!)
                {
                if (Model.PreviousTimes.Any(e => e.Id.ToString().Equals(time.Value)))
                {
                <option selected="selected" value="@time.Value">@time.Text</option>
                }
                else
                {
                <option value="@time.Value">@time.Text</option>
                }
                }
            </select>
            }
            else
            {
            <div class="form-group">
                <label class="control-label">@App.Resources.Views.Shared._Layout.Times</label>
                <select required="required" asp-for="SelectedTimesIds" class="form-control" asp-items="Model.TimesSelectList" multiple="multiple"></select>
            </div>
            }
            }
        </div>
    </div>
</div>
<br/>
<br/>